language: node_js

node_js:
  - "9.3.0"

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github_token: $GH_TOKEN  # Set in travis-ci.org dashboard, marked secure
  target-branch: gh-pages
  local-dir: build
  email: willyamalmeida@hotmail.com
  name: "Deploy Travis"
